// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SupplierViewModel
    {
        /// <summary>
        /// Initializes a new instance of the SupplierViewModel class.
        /// </summary>
        public SupplierViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SupplierViewModel class.
        /// </summary>
        public SupplierViewModel(int? supplierId = default(int?), string supplierName = default(string))
        {
            SupplierId = supplierId;
            SupplierName = supplierName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "supplierId")]
        public int? SupplierId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "supplierName")]
        public string SupplierName { get; set; }

    }
}
